[package]
name = "utils"
version = "0.1.0"
description = "Eiegn utilities."
license = "Apache-2.0"
edition = "2018"

[features]
default = []
mesalock_sgx = ["sgx_tstd"]

[dependencies]
ring         = { version = "0.16.5" }
serde        = { version = "1.0.92" }
serde_derive = { version = "1.0.92" }
sgx_tstd     = { version = "1.1.0", optional = true }
sgx_types    = { version = "1.1.0" }
toml         = { version = "0.5.3" }
