/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TokenAddressHandlerInterface extends ethers.utils.Interface {
  functions: {
    "customL2Token(address)": FunctionFragment;
    "isCustomToken(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "customL2Token",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isCustomToken",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "customL2Token",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCustomToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class TokenAddressHandler extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TokenAddressHandlerInterface;

  functions: {
    customL2Token(arg0: string, overrides?: CallOverrides): Promise<[string]>;

    isCustomToken(
      l1Token: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  customL2Token(arg0: string, overrides?: CallOverrides): Promise<string>;

  isCustomToken(l1Token: string, overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    customL2Token(arg0: string, overrides?: CallOverrides): Promise<string>;

    isCustomToken(l1Token: string, overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    customL2Token(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    isCustomToken(
      l1Token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    customL2Token(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isCustomToken(
      l1Token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
