/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { EigencallDemo, EigencallDemoInterface } from "../EigencallDemo";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "bytes",
        name: "returnValue",
        type: "bytes",
      },
    ],
    name: "Returns",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "input",
        type: "bytes",
      },
    ],
    name: "call_eigenCall",
    outputs: [
      {
        internalType: "bytes",
        name: "",
        type: "bytes",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061037a806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063507f6a5414610030575b600080fd5b6100a76004803603602081101561004657600080fd5b810190808035906020019064010000000081111561006357600080fd5b82018360208201111561007557600080fd5b8035906020019184600183028401116401000000008311171561009757600080fd5b9091929391929390505050610122565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156100e75780820151818401526020810190506100cc565b50505050905090810190601f1680156101145780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b606080606473ffffffffffffffffffffffffffffffffffffffff1663355f7e3785856040518363ffffffff1660e01b815260040180806020018281038252848482818152602001925080828437600081840152601f19601f820116905080830192505050935050505060006040518083038186803b1580156101a357600080fd5b505afa1580156101b7573d6000803e3d6000fd5b505050506040513d6000823e3d601f19601f8201168201806040525060208110156101e157600080fd5b810190808051604051939291908464010000000082111561020157600080fd5b8382019150602082018581111561021757600080fd5b825186600182028301116401000000008211171561023457600080fd5b8083526020830192505050908051906020019080838360005b8381101561026857808201518184015260208101905061024d565b50505050905090810190601f1680156102955780820380516001836020036101000a031916815260200191505b5060405250505090507fc348ae1d964cd62ee0e273d4ea6210915a5447be59744e6c598b0adc2d3b06a8816040518080602001828103825283818151815260200191508051906020019080838360005b838110156103005780820151818401526020810190506102e5565b50505050905090810190601f16801561032d5780820380516001836020036101000a031916815260200191505b509250505060405180910390a1809150509291505056fea264697066735822122070237be22a331d427f0e6999d9ea07eaf7f2502ed3602f13f630e6b57c92e66c64736f6c634300060b0033";

export class EigencallDemo__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<EigencallDemo> {
    return super.deploy(overrides || {}) as Promise<EigencallDemo>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): EigencallDemo {
    return super.attach(address) as EigencallDemo;
  }
  connect(signer: Signer): EigencallDemo__factory {
    return super.connect(signer) as EigencallDemo__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): EigencallDemoInterface {
    return new utils.Interface(_abi) as EigencallDemoInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): EigencallDemo {
    return new Contract(address, _abi, signerOrProvider) as EigencallDemo;
  }
}
