/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IExitTransferCallReceiver,
  IExitTransferCallReceiverInterface,
} from "../IExitTransferCallReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "erc20",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onExitTransfered",
    outputs: [
      {
        internalType: "bytes4",
        name: "",
        type: "bytes4",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IExitTransferCallReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IExitTransferCallReceiverInterface {
    return new utils.Interface(_abi) as IExitTransferCallReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IExitTransferCallReceiver {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IExitTransferCallReceiver;
  }
}
