/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { L2Called, L2CalledInterface } from "../L2Called";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "num",
        type: "uint256",
      },
    ],
    name: "Called",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onTokenTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "num",
        type: "uint256",
      },
    ],
    name: "postDepositHook",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102c2806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80632cf07f821461003b578063a4c0ed3614610069575b600080fd5b6100676004803603602081101561005157600080fd5b810190808035906020019092919050505061010c565b005b61010a6004803603606081101561007f57600080fd5b81019080803573ffffffffffffffffffffffffffffffffffffffff16906020019092919080359060200190929190803590602001906401000000008111156100c657600080fd5b8201836020820111156100d857600080fd5b803590602001918460018302840111640100000000831117156100fa57600080fd5b9091929391929390505050610146565b005b7ffea238a9794376fb3707dbbabe56f0fad5e4110a7839485387c458f2d1aa5d50816040518082815260200191505060405180910390a150565b60008282602081101561015857600080fd5b8101908080359060200190929190505050905060058114156101825761017d8161010c565b610285565b60078114156101f9576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825260158152602001807f73686f756c64206661696c20626563617573652037000000000000000000000081525060200191505060405180910390fd5b6009811415610216575b60005a111561021157610203565b610284565b6040517f08c379a000000000000000000000000000000000000000000000000000000000815260040180806020018281038252600b8152602001807f73686f756c64206661696c00000000000000000000000000000000000000000081525060200191505060405180910390fd5b5b505050505056fea2646970667358221220e065b25f40d08aefa862dfea6487e4be777e7e67167d4fa284168d90bff1c0ae64736f6c634300060b0033";

export class L2Called__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<L2Called> {
    return super.deploy(overrides || {}) as Promise<L2Called>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): L2Called {
    return super.attach(address) as L2Called;
  }
  connect(signer: Signer): L2Called__factory {
    return super.connect(signer) as L2Called__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): L2CalledInterface {
    return new utils.Interface(_abi) as L2CalledInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): L2Called {
    return new Contract(address, _abi, signerOrProvider) as L2Called;
  }
}
