/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  TokenAddressHandler,
  TokenAddressHandlerInterface,
} from "../TokenAddressHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    name: "customL2Token",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "l1Token",
        type: "address",
      },
    ],
    name: "isCustomToken",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class TokenAddressHandler__factory {
  static readonly abi = _abi;
  static createInterface(): TokenAddressHandlerInterface {
    return new utils.Interface(_abi) as TokenAddressHandlerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenAddressHandler {
    return new Contract(address, _abi, signerOrProvider) as TokenAddressHandler;
  }
}
