[package]
name = "attestation"
version = "0.1.0"
description = "Eigen Attestation"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "attestation"
path = "src/lib.rs"

[features]
default = []
mesalock_sgx = ["sgx_tstd", "sgx_tcrypto", "sgx_rand", "sgx_tse"]
eigen_unit_test = []

[dependencies]
anyhow       = { version = "1.0.26" }
base64       = { version = "0.10.1" }
bit-vec      = { version = "0.6.1", default-features = false }
cfg-if       = { version = "0.1.9" }
chrono       = { version = "0.4.6" }
httparse     = { version = "1.3.2", default-features = false }
log          = { version = "0.4.6" }
env_logger   = { version = "0.7.1" }
num-bigint   = { version = "0.2.2" }
rustls       = { version = "0.16.0", features = ["dangerous_configuration"] }
serde_json   = { version = "1.0.39" }
thiserror    = { version = "1.0.9" }
uuid         = { version = "0.8.1", features = ["v4"] }
webpki       = { version = "0.21.0" }
webpki-roots = { version = "0.19.0" }
yasna        = { version = "0.3.0", features = ["bit-vec", "num-bigint", "chrono"] }

sgx_rand    = { version = "1.1.0", optional = true }
sgx_tcrypto = { version = "1.1.0", optional = true }
sgx_tse     = { version = "1.1.0", optional = true }
sgx_tstd    = { version = "1.1.0", features = ["net", "backtrace"], optional = true }
sgx_types   = { version = "1.1.0" }

config = { path = "../config" }
utils  = { path = "../utils" }
